CREATE TABLE CLIENT(
   ID_client INT NOT NULL AUTO_INCREMENT,
   ADRESS_MAIL VARCHAR(50) UNIQUE,
   NOM_COMPTE VARCHAR(50) UNIQUE,
   MDP VARCHAR(50),
   TOKEN_CONNEXION VARCHAR(50),
   VALIDE BOOLEAN,
   DATE_CREATION DATE,
   PRIMARY KEY(ID_client)
);

CREATE TABLE UNIVERS(
   ID_UNIVERS INT NOT NULL AUTO_INCREMENT,
   MDP_SERVEUR VARCHAR(50),
   PRIMARY KEY(ID_UNIVERS)
);

CREATE TABLE VILLAGE(
   ID_VILLAGE INT NOT NULL AUTO_INCREMENT,
   FACTION VARCHAR(50),
   LVL_FORGE SMALLINT,
   LVL_ENTREPOT INT,
   BOIS INT,
   PIERRE VARCHAR(50),
   ORS INT,
   ID_client INT NOT NULL,
   ID_UNIVERS INT NOT NULL,
   PRIMARY KEY(ID_VILLAGE),
   constraint ID_client_village FOREIGN KEY(ID_client) REFERENCES `CLIENT`(ID_client),
   constraint ID_UNIVERS_village FOREIGN KEY(ID_UNIVERS) REFERENCES `UNIVERS`(ID_UNIVERS)
);

CREATE TABLE BOSS(
   ID_BOSS INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR(50),
   DESCRIPTION VARCHAR(50),
   PV INT,
   PM INT,
   PA INT,
   PRIMARY KEY(ID_BOSS)
);

CREATE TABLE MONSTRE(
   ID_MONSTRE INT NOT NULL AUTO_INCREMENT,
   NOM VARCHAR(50),
   ATQ INT,
   DEF INT,
   PV VARCHAR(50),
   PRIMARY KEY(ID_MONSTRE)
);

CREATE TABLE SORT(
   ID_SORT INT NOT NULL AUTO_INCREMENT,
   DESCRIPTION VARCHAR(50),
   DMG INT,
   LANCABLE_SUR_ALLIE BOOLEAN,
   LANCABLE_SUR_ENNEMI BOOLEAN,
   PRIMARY KEY(ID_SORT)
);

CREATE TABLE PERSONNAGE(
   ID_PERSONNAGE INT NOT NULL AUTO_INCREMENT,
   LEVEL INT,
   PV INT,
   POSSEDE BOOLEAN,
   EN_SOIN BOOLEAN,
   EN_ENTRAINEMENT BOOLEAN,
   PV_MAX INT,
   NOM VARCHAR(50),
   CLASSE VARCHAR(50),
   RACE VARCHAR(50),
   PM_MAX INT,
   PA_MAX INT,
   ID_SORT INT NOT NULL,
   PRIMARY KEY(ID_PERSONNAGE),
   constraint ID_SORT_perso FOREIGN KEY(ID_SORT) REFERENCES `SORT`(ID_SORT)
);

CREATE TABLE DONJON(
   ID_DONJON INT NOT NULL AUTO_INCREMENT,
   SEED VARCHAR(50),
   LEVEL_DONJON INT,
   ZONE VARCHAR(50),
   ID_UNIVERS INT NOT NULL,
   ID_BOSS INT NOT NULL,
   ID_MONSTRE INT NOT NULL,
   PRIMARY KEY(ID_DONJON),
   UNIQUE(ID_BOSS),
   constraint ID_UNIVERS_donjon FOREIGN KEY(ID_UNIVERS) REFERENCES `UNIVERS`(ID_UNIVERS),
   constraint ID_BOSS_donjon FOREIGN KEY(ID_BOSS) REFERENCES `BOSS`(ID_BOSS),
   constraint ID_MONSTRE_donjon FOREIGN KEY(ID_MONSTRE) REFERENCES `MONSTRE`(ID_MONSTRE)
);

CREATE TABLE JOUE(
   ID_client INT,
   ID_UNIVERS INT,
   ID_Owner VARCHAR(50),
   PRIMARY KEY(ID_client, ID_UNIVERS),
   constraint ID_CLIENT_joue FOREIGN KEY(ID_client) REFERENCES `CLIENT`(ID_client),
   constraint ID_UNIVERS_joue FOREIGN KEY(ID_UNIVERS) REFERENCES `UNIVERS`(ID_UNIVERS)
);

CREATE TABLE HABITE(
   ID_VILLAGE INT,
   ID_PERSONNAGE INT,
   PRIMARY KEY(ID_VILLAGE, ID_PERSONNAGE),
   constraint ID_VILLAGE_habite FOREIGN KEY(ID_VILLAGE) REFERENCES `VILLAGE`(ID_VILLAGE),
   constraint ID_PERSONNAGE_habite FOREIGN KEY(ID_PERSONNAGE) REFERENCES `PERSONNAGE`(ID_PERSONNAGE)
);

CREATE TABLE SESSION(
   ID_SESSION CHAR,
   ID_CLIENT INT, 
   PRIMARY KEY(ID_SESSION), 
   constraint ID_CLIENT_session FOREIGN KEY(ID_CLIENT) REFERENCES `CLIENT`(ID_client)
);
